### ISSUE TITLE
Issues at training/testing

### ISSUE THREAD

**Issue by LelisThanos** [xinli0928/COVID-Xray#2]
Hello,
i followed the steps to reproduce the results, but the resulting accuracy and loss seem to be really off. Any suggestions? 
The feedback i receive during training is: 
...
----------
train loss: 6.1543, acc: 0.1207
validation loss: 6.2869, acc: 0.1163
Epoch 48/50
----------
train loss: 6.2419, acc: 0.1241
validation loss: 6.3634, acc: 0.1173
Epoch 49/50
----------
train loss: 6.2204, acc: 0.1212
validation loss: 6.3446, acc: 0.1486
Epoch 50/50
----------
train loss: 6.1685, acc: 0.1154
validation loss: 6.3015, acc: 0.1264
0.20224719101123595

**Comment by dongxiaozhu** [comment]
Hi, thanks for your email. Before we spend time to give suggestions,
would you please introduce yourself and the project you are working on?
Commercial or research?

Dongxiao

**Comment by LelisThanos** [comment]
I am Thanos, a research assistant at CERTH, currently performing some research on Covid-19 classification from x-rays.
Thanos
